//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProjetoFabricaCosmeticos.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertFornecedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateFornecedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFornecedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDuplicidadeFornecedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectFornecedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDuplicidadeProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertMateriaPrimaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMateriaPrimaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMateriaPrimaOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDuplicidadeMateriaPrimaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectMateriaPrimaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarItemFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteItemFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDuplicidadeFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDuplicidadeCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectCompraOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ProjetoFabricaCosmeticos.Properties.Settings.Default.ProjetoFabricaCosmeticos_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertFornecedorCompletedEventHandler InsertFornecedorCompleted;
        
        /// <remarks/>
        public event UpdateFornecedorCompletedEventHandler UpdateFornecedorCompleted;
        
        /// <remarks/>
        public event DeleteFornecedorCompletedEventHandler DeleteFornecedorCompleted;
        
        /// <remarks/>
        public event VerificarDuplicidadeFornecedorCompletedEventHandler VerificarDuplicidadeFornecedorCompleted;
        
        /// <remarks/>
        public event SelectFornecedorCompletedEventHandler SelectFornecedorCompleted;
        
        /// <remarks/>
        public event InsertProdutoCompletedEventHandler InsertProdutoCompleted;
        
        /// <remarks/>
        public event UpdateProdutoCompletedEventHandler UpdateProdutoCompleted;
        
        /// <remarks/>
        public event DeleteProdutoCompletedEventHandler DeleteProdutoCompleted;
        
        /// <remarks/>
        public event VerificarDuplicidadeProdutoCompletedEventHandler VerificarDuplicidadeProdutoCompleted;
        
        /// <remarks/>
        public event SelectProdutoCompletedEventHandler SelectProdutoCompleted;
        
        /// <remarks/>
        public event InsertMateriaPrimaCompletedEventHandler InsertMateriaPrimaCompleted;
        
        /// <remarks/>
        public event UpdateMateriaPrimaCompletedEventHandler UpdateMateriaPrimaCompleted;
        
        /// <remarks/>
        public event DeleteMateriaPrimaCompletedEventHandler DeleteMateriaPrimaCompleted;
        
        /// <remarks/>
        public event VerificarDuplicidadeMateriaPrimaCompletedEventHandler VerificarDuplicidadeMateriaPrimaCompleted;
        
        /// <remarks/>
        public event SelectMateriaPrimaCompletedEventHandler SelectMateriaPrimaCompleted;
        
        /// <remarks/>
        public event CadastrarFormulaCompletedEventHandler CadastrarFormulaCompleted;
        
        /// <remarks/>
        public event CadastrarItemFormulaCompletedEventHandler CadastrarItemFormulaCompleted;
        
        /// <remarks/>
        public event DeleteFormulaCompletedEventHandler DeleteFormulaCompleted;
        
        /// <remarks/>
        public event DeleteItemFormulaCompletedEventHandler DeleteItemFormulaCompleted;
        
        /// <remarks/>
        public event VerificarDuplicidadeFormulaCompletedEventHandler VerificarDuplicidadeFormulaCompleted;
        
        /// <remarks/>
        public event SelectFormulaCompletedEventHandler SelectFormulaCompleted;
        
        /// <remarks/>
        public event InsertCompraCompletedEventHandler InsertCompraCompleted;
        
        /// <remarks/>
        public event UpdateCompraCompletedEventHandler UpdateCompraCompleted;
        
        /// <remarks/>
        public event DeleteCompraCompletedEventHandler DeleteCompraCompleted;
        
        /// <remarks/>
        public event VerificarDuplicidadeCompraCompletedEventHandler VerificarDuplicidadeCompraCompleted;
        
        /// <remarks/>
        public event SelectCompraCompletedEventHandler SelectCompraCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertFornecedor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Fornecedor fornecedor) {
            this.Invoke("InsertFornecedor", new object[] {
                        fornecedor});
        }
        
        /// <remarks/>
        public void InsertFornecedorAsync(Fornecedor fornecedor) {
            this.InsertFornecedorAsync(fornecedor, null);
        }
        
        /// <remarks/>
        public void InsertFornecedorAsync(Fornecedor fornecedor, object userState) {
            if ((this.InsertFornecedorOperationCompleted == null)) {
                this.InsertFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertFornecedorOperationCompleted);
            }
            this.InvokeAsync("InsertFornecedor", new object[] {
                        fornecedor}, this.InsertFornecedorOperationCompleted, userState);
        }
        
        private void OnInsertFornecedorOperationCompleted(object arg) {
            if ((this.InsertFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertFornecedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateFornecedor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Fornecedor fornecedor) {
            this.Invoke("UpdateFornecedor", new object[] {
                        fornecedor});
        }
        
        /// <remarks/>
        public void UpdateFornecedorAsync(Fornecedor fornecedor) {
            this.UpdateFornecedorAsync(fornecedor, null);
        }
        
        /// <remarks/>
        public void UpdateFornecedorAsync(Fornecedor fornecedor, object userState) {
            if ((this.UpdateFornecedorOperationCompleted == null)) {
                this.UpdateFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateFornecedorOperationCompleted);
            }
            this.InvokeAsync("UpdateFornecedor", new object[] {
                        fornecedor}, this.UpdateFornecedorOperationCompleted, userState);
        }
        
        private void OnUpdateFornecedorOperationCompleted(object arg) {
            if ((this.UpdateFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateFornecedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteFornecedor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Fornecedor fornecedor) {
            this.Invoke("DeleteFornecedor", new object[] {
                        fornecedor});
        }
        
        /// <remarks/>
        public void DeleteFornecedorAsync(Fornecedor fornecedor) {
            this.DeleteFornecedorAsync(fornecedor, null);
        }
        
        /// <remarks/>
        public void DeleteFornecedorAsync(Fornecedor fornecedor, object userState) {
            if ((this.DeleteFornecedorOperationCompleted == null)) {
                this.DeleteFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFornecedorOperationCompleted);
            }
            this.InvokeAsync("DeleteFornecedor", new object[] {
                        fornecedor}, this.DeleteFornecedorOperationCompleted, userState);
        }
        
        private void OnDeleteFornecedorOperationCompleted(object arg) {
            if ((this.DeleteFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFornecedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/VerificarDuplicidadeFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VerificarDuplicidadeFornecedor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Fornecedor fornecedor, out bool VerificarDuplicidadeFornecedorResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool VerificarDuplicidadeFornecedorResultSpecified) {
            object[] results = this.Invoke("VerificarDuplicidadeFornecedor", new object[] {
                        fornecedor});
            VerificarDuplicidadeFornecedorResult = ((bool)(results[0]));
            VerificarDuplicidadeFornecedorResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeFornecedorAsync(Fornecedor fornecedor) {
            this.VerificarDuplicidadeFornecedorAsync(fornecedor, null);
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeFornecedorAsync(Fornecedor fornecedor, object userState) {
            if ((this.VerificarDuplicidadeFornecedorOperationCompleted == null)) {
                this.VerificarDuplicidadeFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDuplicidadeFornecedorOperationCompleted);
            }
            this.InvokeAsync("VerificarDuplicidadeFornecedor", new object[] {
                        fornecedor}, this.VerificarDuplicidadeFornecedorOperationCompleted, userState);
        }
        
        private void OnVerificarDuplicidadeFornecedorOperationCompleted(object arg) {
            if ((this.VerificarDuplicidadeFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDuplicidadeFornecedorCompleted(this, new VerificarDuplicidadeFornecedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectFornecedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
        public Fornecedor[] SelectFornecedor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Fornecedor filtro) {
            object[] results = this.Invoke("SelectFornecedor", new object[] {
                        filtro});
            return ((Fornecedor[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectFornecedorAsync(Fornecedor filtro) {
            this.SelectFornecedorAsync(filtro, null);
        }
        
        /// <remarks/>
        public void SelectFornecedorAsync(Fornecedor filtro, object userState) {
            if ((this.SelectFornecedorOperationCompleted == null)) {
                this.SelectFornecedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectFornecedorOperationCompleted);
            }
            this.InvokeAsync("SelectFornecedor", new object[] {
                        filtro}, this.SelectFornecedorOperationCompleted, userState);
        }
        
        private void OnSelectFornecedorOperationCompleted(object arg) {
            if ((this.SelectFornecedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectFornecedorCompleted(this, new SelectFornecedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertProduto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            this.Invoke("InsertProduto", new object[] {
                        produto});
        }
        
        /// <remarks/>
        public void InsertProdutoAsync(Produto produto) {
            this.InsertProdutoAsync(produto, null);
        }
        
        /// <remarks/>
        public void InsertProdutoAsync(Produto produto, object userState) {
            if ((this.InsertProdutoOperationCompleted == null)) {
                this.InsertProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertProdutoOperationCompleted);
            }
            this.InvokeAsync("InsertProduto", new object[] {
                        produto}, this.InsertProdutoOperationCompleted, userState);
        }
        
        private void OnInsertProdutoOperationCompleted(object arg) {
            if ((this.InsertProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateProduto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            this.Invoke("UpdateProduto", new object[] {
                        produto});
        }
        
        /// <remarks/>
        public void UpdateProdutoAsync(Produto produto) {
            this.UpdateProdutoAsync(produto, null);
        }
        
        /// <remarks/>
        public void UpdateProdutoAsync(Produto produto, object userState) {
            if ((this.UpdateProdutoOperationCompleted == null)) {
                this.UpdateProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProdutoOperationCompleted);
            }
            this.InvokeAsync("UpdateProduto", new object[] {
                        produto}, this.UpdateProdutoOperationCompleted, userState);
        }
        
        private void OnUpdateProdutoOperationCompleted(object arg) {
            if ((this.UpdateProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteProduto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            this.Invoke("DeleteProduto", new object[] {
                        produto});
        }
        
        /// <remarks/>
        public void DeleteProdutoAsync(Produto produto) {
            this.DeleteProdutoAsync(produto, null);
        }
        
        /// <remarks/>
        public void DeleteProdutoAsync(Produto produto, object userState) {
            if ((this.DeleteProdutoOperationCompleted == null)) {
                this.DeleteProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProdutoOperationCompleted);
            }
            this.InvokeAsync("DeleteProduto", new object[] {
                        produto}, this.DeleteProdutoOperationCompleted, userState);
        }
        
        private void OnDeleteProdutoOperationCompleted(object arg) {
            if ((this.DeleteProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProdutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/VerificarDuplicidadeProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VerificarDuplicidadeProduto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto, out bool VerificarDuplicidadeProdutoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool VerificarDuplicidadeProdutoResultSpecified) {
            object[] results = this.Invoke("VerificarDuplicidadeProduto", new object[] {
                        produto});
            VerificarDuplicidadeProdutoResult = ((bool)(results[0]));
            VerificarDuplicidadeProdutoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeProdutoAsync(Produto produto) {
            this.VerificarDuplicidadeProdutoAsync(produto, null);
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeProdutoAsync(Produto produto, object userState) {
            if ((this.VerificarDuplicidadeProdutoOperationCompleted == null)) {
                this.VerificarDuplicidadeProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDuplicidadeProdutoOperationCompleted);
            }
            this.InvokeAsync("VerificarDuplicidadeProduto", new object[] {
                        produto}, this.VerificarDuplicidadeProdutoOperationCompleted, userState);
        }
        
        private void OnVerificarDuplicidadeProdutoOperationCompleted(object arg) {
            if ((this.VerificarDuplicidadeProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDuplicidadeProdutoCompleted(this, new VerificarDuplicidadeProdutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
        public Produto[] SelectProduto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto filtro) {
            object[] results = this.Invoke("SelectProduto", new object[] {
                        filtro});
            return ((Produto[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectProdutoAsync(Produto filtro) {
            this.SelectProdutoAsync(filtro, null);
        }
        
        /// <remarks/>
        public void SelectProdutoAsync(Produto filtro, object userState) {
            if ((this.SelectProdutoOperationCompleted == null)) {
                this.SelectProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectProdutoOperationCompleted);
            }
            this.InvokeAsync("SelectProduto", new object[] {
                        filtro}, this.SelectProdutoOperationCompleted, userState);
        }
        
        private void OnSelectProdutoOperationCompleted(object arg) {
            if ((this.SelectProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectProdutoCompleted(this, new SelectProdutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertMateriaPrima", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertMateriaPrima([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MateriaPrima materiaprima) {
            this.Invoke("InsertMateriaPrima", new object[] {
                        materiaprima});
        }
        
        /// <remarks/>
        public void InsertMateriaPrimaAsync(MateriaPrima materiaprima) {
            this.InsertMateriaPrimaAsync(materiaprima, null);
        }
        
        /// <remarks/>
        public void InsertMateriaPrimaAsync(MateriaPrima materiaprima, object userState) {
            if ((this.InsertMateriaPrimaOperationCompleted == null)) {
                this.InsertMateriaPrimaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertMateriaPrimaOperationCompleted);
            }
            this.InvokeAsync("InsertMateriaPrima", new object[] {
                        materiaprima}, this.InsertMateriaPrimaOperationCompleted, userState);
        }
        
        private void OnInsertMateriaPrimaOperationCompleted(object arg) {
            if ((this.InsertMateriaPrimaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertMateriaPrimaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateMateriaPrima", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMateriaPrima([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MateriaPrima materiaprima) {
            this.Invoke("UpdateMateriaPrima", new object[] {
                        materiaprima});
        }
        
        /// <remarks/>
        public void UpdateMateriaPrimaAsync(MateriaPrima materiaprima) {
            this.UpdateMateriaPrimaAsync(materiaprima, null);
        }
        
        /// <remarks/>
        public void UpdateMateriaPrimaAsync(MateriaPrima materiaprima, object userState) {
            if ((this.UpdateMateriaPrimaOperationCompleted == null)) {
                this.UpdateMateriaPrimaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMateriaPrimaOperationCompleted);
            }
            this.InvokeAsync("UpdateMateriaPrima", new object[] {
                        materiaprima}, this.UpdateMateriaPrimaOperationCompleted, userState);
        }
        
        private void OnUpdateMateriaPrimaOperationCompleted(object arg) {
            if ((this.UpdateMateriaPrimaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMateriaPrimaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteMateriaPrima", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteMateriaPrima([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MateriaPrima materiaprima) {
            this.Invoke("DeleteMateriaPrima", new object[] {
                        materiaprima});
        }
        
        /// <remarks/>
        public void DeleteMateriaPrimaAsync(MateriaPrima materiaprima) {
            this.DeleteMateriaPrimaAsync(materiaprima, null);
        }
        
        /// <remarks/>
        public void DeleteMateriaPrimaAsync(MateriaPrima materiaprima, object userState) {
            if ((this.DeleteMateriaPrimaOperationCompleted == null)) {
                this.DeleteMateriaPrimaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMateriaPrimaOperationCompleted);
            }
            this.InvokeAsync("DeleteMateriaPrima", new object[] {
                        materiaprima}, this.DeleteMateriaPrimaOperationCompleted, userState);
        }
        
        private void OnDeleteMateriaPrimaOperationCompleted(object arg) {
            if ((this.DeleteMateriaPrimaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMateriaPrimaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/VerificarDuplicidadeMateriaPrima", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VerificarDuplicidadeMateriaPrima([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MateriaPrima materiaprima, out bool VerificarDuplicidadeMateriaPrimaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool VerificarDuplicidadeMateriaPrimaResultSpecified) {
            object[] results = this.Invoke("VerificarDuplicidadeMateriaPrima", new object[] {
                        materiaprima});
            VerificarDuplicidadeMateriaPrimaResult = ((bool)(results[0]));
            VerificarDuplicidadeMateriaPrimaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeMateriaPrimaAsync(MateriaPrima materiaprima) {
            this.VerificarDuplicidadeMateriaPrimaAsync(materiaprima, null);
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeMateriaPrimaAsync(MateriaPrima materiaprima, object userState) {
            if ((this.VerificarDuplicidadeMateriaPrimaOperationCompleted == null)) {
                this.VerificarDuplicidadeMateriaPrimaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDuplicidadeMateriaPrimaOperationCompleted);
            }
            this.InvokeAsync("VerificarDuplicidadeMateriaPrima", new object[] {
                        materiaprima}, this.VerificarDuplicidadeMateriaPrimaOperationCompleted, userState);
        }
        
        private void OnVerificarDuplicidadeMateriaPrimaOperationCompleted(object arg) {
            if ((this.VerificarDuplicidadeMateriaPrimaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDuplicidadeMateriaPrimaCompleted(this, new VerificarDuplicidadeMateriaPrimaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectMateriaPrima", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
        public MateriaPrima[] SelectMateriaPrima([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MateriaPrima filtro) {
            object[] results = this.Invoke("SelectMateriaPrima", new object[] {
                        filtro});
            return ((MateriaPrima[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectMateriaPrimaAsync(MateriaPrima filtro) {
            this.SelectMateriaPrimaAsync(filtro, null);
        }
        
        /// <remarks/>
        public void SelectMateriaPrimaAsync(MateriaPrima filtro, object userState) {
            if ((this.SelectMateriaPrimaOperationCompleted == null)) {
                this.SelectMateriaPrimaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectMateriaPrimaOperationCompleted);
            }
            this.InvokeAsync("SelectMateriaPrima", new object[] {
                        filtro}, this.SelectMateriaPrimaOperationCompleted, userState);
        }
        
        private void OnSelectMateriaPrimaOperationCompleted(object arg) {
            if ((this.SelectMateriaPrimaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectMateriaPrimaCompleted(this, new SelectMateriaPrimaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarFormula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarFormula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            this.Invoke("CadastrarFormula", new object[] {
                        produto});
        }
        
        /// <remarks/>
        public void CadastrarFormulaAsync(Produto produto) {
            this.CadastrarFormulaAsync(produto, null);
        }
        
        /// <remarks/>
        public void CadastrarFormulaAsync(Produto produto, object userState) {
            if ((this.CadastrarFormulaOperationCompleted == null)) {
                this.CadastrarFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarFormulaOperationCompleted);
            }
            this.InvokeAsync("CadastrarFormula", new object[] {
                        produto}, this.CadastrarFormulaOperationCompleted, userState);
        }
        
        private void OnCadastrarFormulaOperationCompleted(object arg) {
            if ((this.CadastrarFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarFormulaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CadastrarItemFormula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarItemFormula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MateriaPrima materiaPrima) {
            this.Invoke("CadastrarItemFormula", new object[] {
                        materiaPrima});
        }
        
        /// <remarks/>
        public void CadastrarItemFormulaAsync(MateriaPrima materiaPrima) {
            this.CadastrarItemFormulaAsync(materiaPrima, null);
        }
        
        /// <remarks/>
        public void CadastrarItemFormulaAsync(MateriaPrima materiaPrima, object userState) {
            if ((this.CadastrarItemFormulaOperationCompleted == null)) {
                this.CadastrarItemFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarItemFormulaOperationCompleted);
            }
            this.InvokeAsync("CadastrarItemFormula", new object[] {
                        materiaPrima}, this.CadastrarItemFormulaOperationCompleted, userState);
        }
        
        private void OnCadastrarItemFormulaOperationCompleted(object arg) {
            if ((this.CadastrarItemFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarItemFormulaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteFormula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteFormula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            this.Invoke("DeleteFormula", new object[] {
                        produto});
        }
        
        /// <remarks/>
        public void DeleteFormulaAsync(Produto produto) {
            this.DeleteFormulaAsync(produto, null);
        }
        
        /// <remarks/>
        public void DeleteFormulaAsync(Produto produto, object userState) {
            if ((this.DeleteFormulaOperationCompleted == null)) {
                this.DeleteFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFormulaOperationCompleted);
            }
            this.InvokeAsync("DeleteFormula", new object[] {
                        produto}, this.DeleteFormulaOperationCompleted, userState);
        }
        
        private void OnDeleteFormulaOperationCompleted(object arg) {
            if ((this.DeleteFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFormulaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteItemFormula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteItemFormula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MateriaPrima materiaPrima) {
            this.Invoke("DeleteItemFormula", new object[] {
                        materiaPrima});
        }
        
        /// <remarks/>
        public void DeleteItemFormulaAsync(MateriaPrima materiaPrima) {
            this.DeleteItemFormulaAsync(materiaPrima, null);
        }
        
        /// <remarks/>
        public void DeleteItemFormulaAsync(MateriaPrima materiaPrima, object userState) {
            if ((this.DeleteItemFormulaOperationCompleted == null)) {
                this.DeleteItemFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteItemFormulaOperationCompleted);
            }
            this.InvokeAsync("DeleteItemFormula", new object[] {
                        materiaPrima}, this.DeleteItemFormulaOperationCompleted, userState);
        }
        
        private void OnDeleteItemFormulaOperationCompleted(object arg) {
            if ((this.DeleteItemFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteItemFormulaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/VerificarDuplicidadeFormula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VerificarDuplicidadeFormula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto, out bool VerificarDuplicidadeFormulaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool VerificarDuplicidadeFormulaResultSpecified) {
            object[] results = this.Invoke("VerificarDuplicidadeFormula", new object[] {
                        produto});
            VerificarDuplicidadeFormulaResult = ((bool)(results[0]));
            VerificarDuplicidadeFormulaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeFormulaAsync(Produto produto) {
            this.VerificarDuplicidadeFormulaAsync(produto, null);
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeFormulaAsync(Produto produto, object userState) {
            if ((this.VerificarDuplicidadeFormulaOperationCompleted == null)) {
                this.VerificarDuplicidadeFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDuplicidadeFormulaOperationCompleted);
            }
            this.InvokeAsync("VerificarDuplicidadeFormula", new object[] {
                        produto}, this.VerificarDuplicidadeFormulaOperationCompleted, userState);
        }
        
        private void OnVerificarDuplicidadeFormulaOperationCompleted(object arg) {
            if ((this.VerificarDuplicidadeFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDuplicidadeFormulaCompleted(this, new VerificarDuplicidadeFormulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectFormula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
        public MateriaPrima[] SelectFormula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto filtro) {
            object[] results = this.Invoke("SelectFormula", new object[] {
                        filtro});
            return ((MateriaPrima[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectFormulaAsync(Produto filtro) {
            this.SelectFormulaAsync(filtro, null);
        }
        
        /// <remarks/>
        public void SelectFormulaAsync(Produto filtro, object userState) {
            if ((this.SelectFormulaOperationCompleted == null)) {
                this.SelectFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectFormulaOperationCompleted);
            }
            this.InvokeAsync("SelectFormula", new object[] {
                        filtro}, this.SelectFormulaOperationCompleted, userState);
        }
        
        private void OnSelectFormulaOperationCompleted(object arg) {
            if ((this.SelectFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectFormulaCompleted(this, new SelectFormulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertCompra([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Compra compra) {
            this.Invoke("InsertCompra", new object[] {
                        compra});
        }
        
        /// <remarks/>
        public void InsertCompraAsync(Compra compra) {
            this.InsertCompraAsync(compra, null);
        }
        
        /// <remarks/>
        public void InsertCompraAsync(Compra compra, object userState) {
            if ((this.InsertCompraOperationCompleted == null)) {
                this.InsertCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCompraOperationCompleted);
            }
            this.InvokeAsync("InsertCompra", new object[] {
                        compra}, this.InsertCompraOperationCompleted, userState);
        }
        
        private void OnInsertCompraOperationCompleted(object arg) {
            if ((this.InsertCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCompra([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Compra compra) {
            this.Invoke("UpdateCompra", new object[] {
                        compra});
        }
        
        /// <remarks/>
        public void UpdateCompraAsync(Compra compra) {
            this.UpdateCompraAsync(compra, null);
        }
        
        /// <remarks/>
        public void UpdateCompraAsync(Compra compra, object userState) {
            if ((this.UpdateCompraOperationCompleted == null)) {
                this.UpdateCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCompraOperationCompleted);
            }
            this.InvokeAsync("UpdateCompra", new object[] {
                        compra}, this.UpdateCompraOperationCompleted, userState);
        }
        
        private void OnUpdateCompraOperationCompleted(object arg) {
            if ((this.UpdateCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCompra([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Compra compra) {
            this.Invoke("DeleteCompra", new object[] {
                        compra});
        }
        
        /// <remarks/>
        public void DeleteCompraAsync(Compra compra) {
            this.DeleteCompraAsync(compra, null);
        }
        
        /// <remarks/>
        public void DeleteCompraAsync(Compra compra, object userState) {
            if ((this.DeleteCompraOperationCompleted == null)) {
                this.DeleteCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCompraOperationCompleted);
            }
            this.InvokeAsync("DeleteCompra", new object[] {
                        compra}, this.DeleteCompraOperationCompleted, userState);
        }
        
        private void OnDeleteCompraOperationCompleted(object arg) {
            if ((this.DeleteCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/VerificarDuplicidadeCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VerificarDuplicidadeCompra([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Compra compra, out bool VerificarDuplicidadeCompraResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool VerificarDuplicidadeCompraResultSpecified) {
            object[] results = this.Invoke("VerificarDuplicidadeCompra", new object[] {
                        compra});
            VerificarDuplicidadeCompraResult = ((bool)(results[0]));
            VerificarDuplicidadeCompraResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeCompraAsync(Compra compra) {
            this.VerificarDuplicidadeCompraAsync(compra, null);
        }
        
        /// <remarks/>
        public void VerificarDuplicidadeCompraAsync(Compra compra, object userState) {
            if ((this.VerificarDuplicidadeCompraOperationCompleted == null)) {
                this.VerificarDuplicidadeCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDuplicidadeCompraOperationCompleted);
            }
            this.InvokeAsync("VerificarDuplicidadeCompra", new object[] {
                        compra}, this.VerificarDuplicidadeCompraOperationCompleted, userState);
        }
        
        private void OnVerificarDuplicidadeCompraOperationCompleted(object arg) {
            if ((this.VerificarDuplicidadeCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDuplicidadeCompraCompleted(this, new VerificarDuplicidadeCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
        public Compra[] SelectCompra([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Compra compra) {
            object[] results = this.Invoke("SelectCompra", new object[] {
                        compra});
            return ((Compra[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectCompraAsync(Compra compra) {
            this.SelectCompraAsync(compra, null);
        }
        
        /// <remarks/>
        public void SelectCompraAsync(Compra compra, object userState) {
            if ((this.SelectCompraOperationCompleted == null)) {
                this.SelectCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectCompraOperationCompleted);
            }
            this.InvokeAsync("SelectCompra", new object[] {
                        compra}, this.SelectCompraOperationCompleted, userState);
        }
        
        private void OnSelectCompraOperationCompleted(object arg) {
            if ((this.SelectCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCompraCompleted(this, new SelectCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
    public partial class Fornecedor {
        
        private string bairroField;
        
        private string cepField;
        
        private string cidadeField;
        
        private string cnpjField;
        
        private string complementoField;
        
        private Compra[] compraField;
        
        private string emailField;
        
        private string estadoField;
        
        private int idField;
        
        private string logradouroField;
        
        private string razaoSocialField;
        
        private string telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Compra[] compra {
            get {
                return this.compraField;
            }
            set {
                this.compraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string razaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
    public partial class Compra {
        
        private Fornecedor fornecedorField;
        
        private MateriaPrima materiaPrimaField;
        
        private double precoField;
        
        private int quantidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Fornecedor fornecedor {
            get {
                return this.fornecedorField;
            }
            set {
                this.fornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MateriaPrima materiaPrima {
            get {
                return this.materiaPrimaField;
            }
            set {
                this.materiaPrimaField = value;
            }
        }
        
        /// <remarks/>
        public double preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public int quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
    public partial class MateriaPrima {
        
        private Compra[] compraField;
        
        private string descricaoField;
        
        private int estoqueAtualField;
        
        private int idField;
        
        private string loteField;
        
        private string nomeField;
        
        private Produto[] produtoField;
        
        private System.DateTime validadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Compra[] compra {
            get {
                return this.compraField;
            }
            set {
                this.compraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int estoqueAtual {
            get {
                return this.estoqueAtualField;
            }
            set {
                this.estoqueAtualField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Produto[] produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime validade {
            get {
                return this.validadeField;
            }
            set {
                this.validadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Classes_Basicas")]
    public partial class Produto {
        
        private string descricaoField;
        
        private int idField;
        
        private MateriaPrima[] materiaPrimaField;
        
        private string nomeField;
        
        private string unidadeFornecimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MateriaPrima[] materiaPrima {
            get {
                return this.materiaPrimaField;
            }
            set {
                this.materiaPrimaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unidadeFornecimento {
            get {
                return this.unidadeFornecimentoField;
            }
            set {
                this.unidadeFornecimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertFornecedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateFornecedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteFornecedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarDuplicidadeFornecedorCompletedEventHandler(object sender, VerificarDuplicidadeFornecedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDuplicidadeFornecedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDuplicidadeFornecedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeFornecedorResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeFornecedorResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SelectFornecedorCompletedEventHandler(object sender, SelectFornecedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectFornecedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectFornecedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Fornecedor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Fornecedor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteProdutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarDuplicidadeProdutoCompletedEventHandler(object sender, VerificarDuplicidadeProdutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDuplicidadeProdutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDuplicidadeProdutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeProdutoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeProdutoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SelectProdutoCompletedEventHandler(object sender, SelectProdutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectProdutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectProdutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Produto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Produto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertMateriaPrimaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateMateriaPrimaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteMateriaPrimaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarDuplicidadeMateriaPrimaCompletedEventHandler(object sender, VerificarDuplicidadeMateriaPrimaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDuplicidadeMateriaPrimaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDuplicidadeMateriaPrimaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeMateriaPrimaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeMateriaPrimaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SelectMateriaPrimaCompletedEventHandler(object sender, SelectMateriaPrimaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectMateriaPrimaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectMateriaPrimaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MateriaPrima[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MateriaPrima[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarFormulaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarItemFormulaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteFormulaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteItemFormulaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarDuplicidadeFormulaCompletedEventHandler(object sender, VerificarDuplicidadeFormulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDuplicidadeFormulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDuplicidadeFormulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeFormulaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeFormulaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SelectFormulaCompletedEventHandler(object sender, SelectFormulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectFormulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectFormulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MateriaPrima[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MateriaPrima[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VerificarDuplicidadeCompraCompletedEventHandler(object sender, VerificarDuplicidadeCompraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDuplicidadeCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDuplicidadeCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeCompraResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool VerificarDuplicidadeCompraResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SelectCompraCompletedEventHandler(object sender, SelectCompraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Compra[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Compra[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591